#
# Your Crowdin credentials
#
project_id: "28"
api_token_env: CROWDIN_API_TOKEN
base_path: "."
base_url: "https://jenkins.crowdin.com/"

preserve_hierarchy: true

#
# Files configuration
#
files:
  - source: "xliff/*.xlf"
    translation: "xliff/%locale%.xlf"
    ignore:
      - "xliff/%locale%.xlf"
    type: "xliff"

