name: Tests

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - alpha
      - beta
  pull_request:
    branches:
      - main
      - alpha
      - beta

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        cache: 'npm'

    - name: Check spelling of file.txt
      uses: crate-ci/typos@v1.12.12

    - name: Install dependencies
      run: npm ci

    - name: Install playwright deps
      run: |
        npx playwright install-deps
        npx playwright install

    - run: npm run build --if-present

    - run: npm run lint

    - run: npm test

    - run: npm run build-storybook

    - name: Deploy to Netlify
      id: netlifydeploy
      uses: nwtgck/actions-netlify@v1.2
      with:
        publish-dir: './storybook-static'
        production-branch: main
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
        alias: deploy-preview-${{ github.event.number }}
        enable-pull-request-comment: true
        enable-commit-comment: true
        overwrites-pull-request-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    - run: npx test-storybook --maxWorkers=2 --coverage
      env:
        TARGET_URL: ${{ steps.netlifydeploy.outputs.deploy-url}}
