name: Tests

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - alpha
      - beta
  pull_request:
    branches:
      - main
      - alpha
      - beta

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        cache: 'npm'

    - name: Check spelling of file.txt
      uses: crate-ci/typos@v1.12.12

    - name: Install dependencies
      run: npm ci

    - run: npm run build --if-present

    - run: npm run lint

    - run: npm run build-storybook

    - name: Deploy to Netlify Preview
      id: netlify-pr-deploy
      if: github.event_name == 'pull_request'
      uses: jsmrcaga/action-netlify-deploy@v1.8.2
      with:
        NETLIFY_DEPLOY_MESSAGE: "${{github.event.pull_request.title}} - https://github.com/jenkins-infra/jenkins-io-components/pull/${{ github.event.number }}"
        DEPLOY_ALIAS: deploy-preview-${{ github.event.number }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        build_directory: './storybook-static'

    - name: Deploy to Netlify
      id: netlify-deploy
      if: github.event_name != 'pull_request'
      uses: jsmrcaga/action-netlify-deploy@v1.8.2
      with:
        NETLIFY_DEPLOY_TO_PROD: true
        NETLIFY_DEPLOY_MESSAGE: "Deploy from GitHub Actions"
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        build_directory: './storybook-static'

    - name: Mark PR Site Deployed
      if: github.event_name == 'pull_request'
      uses: chrnorm/deployment-action@v2
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
        initial-status: success
        environment: preview
        environment-url: "https://deploy-preview-${{ github.event.number }}--jenkins-io-components.netlify.app"

    - name: Mark Site Deployed
      if: github.event_name != 'pull_request'
      uses: chrnorm/deployment-action@v2
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
        initial-status: success
        environment: production
        environment-url: "https://jenkins-io-components.netlify.app"

    - run: npx test-storybook --maxWorkers=2 --coverage
      if: github.event_name == 'pull_request'
      env:
        TARGET_URL: "https://deploy-preview-${{ github.event.number }}--jenkins-io-components.netlify.app"

    - run: npx test-storybook --maxWorkers=2 --coverage
      if: github.event_name != 'pull_request'
      env:
        TARGET_URL: "https://jenkins-io-components.netlify.app"
