name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.27.1-focal
    services:
      nginx:
        image: nginx
        ports:
          - 80:80
        volumes:
          - "/github/workspace/storybook-static:/usr/share/nginx/html"

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        cache: 'npm'

    - name: Check spelling of file.txt
      uses: crate-ci/typos@master

    - name: Install dependencies
      run: npm ci

    - run: npm run build --if-present

    - run: npm run lint

    - run: npm test

    - run: npm run build-storybook

    - run: npx test-storybook --maxWorkers=2 --coverage
      env:
        TARGET_URL: http://nginx

    - uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        verbose: true
