name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        cache: 'npm'

    - name: Check spelling of file.txt
      uses: crate-ci/typos@master

    - name: Install dependencies
      run: |
        npm ci
        npx playwright install-deps
        npx playwright install

    - run: npm run build --if-present

    - run: npm run lint

    - run: npm test

    - run: npm run test-storybook:ci

    - uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        verbose: true
